#!/bin/bash

L4I_BRANCH=master

function main()  {
	if [ "$1" != "new" ] && [ "$1" != "NEW" ] && [ -f "./artisan" ]; then
		php artisan "$@"
	else
		makeTemp

		wget -N --no-check-certificate -O $SCRIPT https://raw.github.com/antonioribeiro/l4i/$L4I_BRANCH/installFour.sh &> $LOG
		checkErrors "An error while downloading i4l script, please check the log file at $LOG"
		bash $SCRIPT

		removeTemp
	fi
}

function makeTemp() {
	SCRIPT=`mktemp`

	if [ "$SCRIPT" == "" ]; then
		SCRIPT=/tmp/$(basename $0).$$.tmp
	fi

	if [ "$SCRIPT" == "" ]; then
		rm -f /tmp/installFour.sh &> /dev/null
		sudo rm -f /tmp/installFour.sh &> /dev/null
		SCRIPT=/tmp/installFour.sh
	fi

	LOG=$SCRIPT.log
}

function checkErrors() {
	if [ $? -gt 0 ]; then
		echo $1
		abortIt
	fi
}

function removeTemp() {
	rm $SCRIPT
}

main $1
