#!/bin/bash

L4I_BRANCH=master

ARTISAN_APP=./artisan

function main()  {
	findArtisan


	if [ "$1" != "new" ] && [ "$1" != "NEW" ] && [ "$1" != "New" ] && [ "$ARTISAN_APP" != "" ] && [ -f $ARTISAN_APP ]; then
		echo "artisan found at $ARTISAN_APP"
 		php $ARTISAN_APP $@
	else
		makeTemp

		wget -N --no-check-certificate -O $SCRIPT https://raw.github.com/antonioribeiro/l4i/$L4I_BRANCH/installFour.sh &> $LOG
		checkErrors "An error while downloading i4l script, please check the log file at $LOG"
		bash $SCRIPT

		removeTemp
	fi
}

function findArtisan() {
	artisan=$ARTISAN_APP
	ARTISAN_APP=

	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../../../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../../../../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../../../../../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../../../../../../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	artisan=../../../../../../../artisan
	[ "$ARTISAN_APP" == "" ] && [ -f $artisan ] && ARTISAN_APP=$artisan

	# if [[ "$ARTISAN_APP" != "" ]]; then
	# 	dir=`dirname $ARTISAN_APP`
	# 	dir=$(dirname )
	# 	if [[]]	
	# fi
}

function makeTemp() {
	SCRIPT=`mktemp`

	if [ "$SCRIPT" == "" ]; then
		SCRIPT=/tmp/$(basename $0).$$.tmp
	fi

	if [ "$SCRIPT" == "" ]; then
		rm -f /tmp/installFour.sh &> /dev/null
		sudo rm -f /tmp/installFour.sh &> /dev/null
		SCRIPT=/tmp/installFour.sh
	fi

	LOG=$SCRIPT.log
}

function checkErrors() {
	if [ $? -gt 0 ]; then
		echo $1
		abortIt
	fi
}

function removeTemp() {
	rm $SCRIPT
}

main $@
